diffusion_model:
  input_dim: 64
  time_embedding_dim: 8  # This needs to have the same dimension as the time_embedding configuration
  num_hidden_layers: 4
  hidden_layer_shapes: [128, 128, 128, 128] 
  # activation: ReLU
  # dropout: 0.0  # TODO: Implement dropout

  time_embedding:
    type: sinusoidal 
    dim: 8

  noise_scheduler:
    type: linear
    beta_start: 0.0001 
    beta_stop: 1.0
    T: 1000

training:
  batch_size: 32
  num_epochs: 10000
  optimizer_cls: Adam
  optimizer_kwargs:
    lr: 0.001
  criterion: MSELoss
  shuffle_dl: true
  checkpoint_iterations: 100
  logging_iterations: 10
