property_model:
  class_name: TimeDependentPropertyModel
  input_dim: 64
  time_embedding_dim: 8
  output_dim: 1
  num_hidden_layers: 3
  hidden_layer_shapes: [64, 64, 64]
  # activation: ReLU
  # dropout: 0.0  # TODO: Implement dropout

  noise_scheduler:
    type: linear
    beta_start: 0.0001 
    beta_stop: 1.0
    T: 1000

  time_embedding:
    dim: 8
    type: sinusoidal

training:
  batch_size: 128
  num_epochs: 10000 
  optimizer_cls: Adam
  optimizer_kwargs:
    lr: 0.001
  criterion: MSELoss
  shuffle_train_dl: true
  shuffle_test_dl: false
  logging_iterations: 10
  checkpoint_iterations: 100
